[package]
name = "irondragon"
version = "0.1.0"
authors = ["Jan Vandepitte"]

[dependencies]
iron = "*"
router = "*"
mount = "*"
staticfile = "*"
RobotS = { version = "*",  git = "https://github.com/gamazeps/RobotS" }
